// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceTravel.Models;

#nullable disable

namespace SpaceTravel.Migrations
{
    [DbContext(typeof(SpaceTravelContext))]
    [Migration("20230423221943_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpaceTravel.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("DestinationId");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            Name = "Carina Nebula",
                            Price = "$1,295",
                            Url = "dfhdfj"
                        },
                        new
                        {
                            DestinationId = 2,
                            Name = "Helix Nebula",
                            Price = "$1,495",
                            Url = "https://images.nasa.gov/details/PIA09178"
                        },
                        new
                        {
                            DestinationId = 3,
                            Name = "Mars",
                            Price = "$1,095",
                            Url = "dhhhf"
                        },
                        new
                        {
                            DestinationId = 4,
                            Name = "Neptune ",
                            Price = "$2,295",
                            Url = "https://images.nasa.gov/details/PIA01492"
                        },
                        new
                        {
                            DestinationId = 5,
                            Name = "Aurora Australis",
                            Price = "$1,895",
                            Url = "https://images.nasa.gov/details/iss029e008433"
                        },
                        new
                        {
                            DestinationId = 6,
                            Name = "Carina Nebula2",
                            Price = "$1,495",
                            Url = "dsgsdg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
